language: python

python:
  - 2.7
  - 3.6
  
services: postgresql

env:
  global:
    - DJANGO_SETTINGS_MODULE="apps.server.settings.development"
    - PYTHONPATH="${HOME}/builds/noiseMap/noise-map-server"
    - DEFAULT_DATABASE_NAME="travisdb"
    - DEFAULT_DATABASE_PASSWORD=""
  
install:
  - pip install -r requirements.txt
  
before_script:
  - psql -U postgres -c "CREATE DATABASE ${DEFAULT_DATABASE_NAME}"
  - psql -U postgres -c "CREATE EXTENSION postgis"
  
script:
  - python manage.py migrate
