# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 18:35
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noisedata', '0002_auto_20170219_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noisedata',
            name='bounding_box',
        ),
        migrations.AddField(
            model_name='noisedata',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noisedata',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='noisedata',
            name='center',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
