# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noisedata', '0003_auto_20170219_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noisedata',
            name='center',
        ),
    ]
