# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 13:30
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noisedata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoiseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('elevation', models.FloatField()),
                ('bounding_box', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('noise_mean_day', models.FloatField()),
                ('noise_mean_evening', models.FloatField()),
                ('noise_mean_night', models.FloatField()),
                ('noise_weighted_24h', models.FloatField()),
                ('noise_mean_24h', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='dummy',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(dim=3, null=True, srid=4326),
        ),
    ]
